# Generated by Django 5.1.1 on 2024-10-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Укажите заголовок поста",
                        max_length=150,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Укажите содержание поста",
                        verbose_name="Содержание поста",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображения для превью",
                        null=True,
                        upload_to="blog/image",
                        verbose_name="Превью",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("publication_sign", models.BooleanField(default=True)),
                (
                    "views_counter",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Укажите количество просмотров",
                        verbose_name="Счётчик просмотров",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост в блоге",
                "verbose_name_plural": "Посты в блоге",
                "ordering": [
                    "title",
                    "content",
                    "created_at",
                    "publication_sign",
                    "views_counter",
                ],
            },
        ),
    ]
