# Generated by Django 5.1.1 on 2024-10-06 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование категории', max_length=150, verbose_name='Наименование категории')),
                ('description', models.TextField(help_text='Введите описание категории', verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование продукта', max_length=150, verbose_name='Наименование продукта')),
                ('description', models.TextField(help_text='Введите описание продукта', verbose_name='Описание продукта')),
                ('image', models.ImageField(blank=True, help_text='Введите описание продукта', null=True, upload_to='catalog/image', verbose_name='Описание продукта')),
                ('price', models.IntegerField(help_text='Введите цену целым числом', verbose_name='Цена')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Введите категорию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['category', 'name', 'price', 'created_at'],
            },
        ),
    ]
